//! Generated JSON schemas and validators for the stable front-end shell.

use std::collections::BTreeMap;

use schemars::JsonSchema;
use schemars::Schema;
use serde::Deserialize;
use serde::Serialize;
use serde_json::Error;
use serde_json::Value;
use serde_json::json;

use crate::alert::LostIntegrationEvidenceAlert;
use crate::coordination_identity::CoordinationIdentityRejection;
use crate::ledger::CanonicalWorktreeRoot;
use crate::output;
use crate::output::CLOSED_VALUE_SELECTOR_TRANSFORM_FAILURE_KEY;
use crate::output::IdentityPayload;
use crate::output::IntegrationPayload;
use crate::output::OUTPUT_CONTRACT_VERSION;
use crate::output::OutputEnvelope;
use crate::output::ReplayFailurePayload;
use crate::output::ReservationLifecycleQueryPayload;
use crate::output::ResolvePayload;
use crate::reservation::IntegrationEvidenceStatus;
use crate::reservation::IntegrationProof;
use crate::reservation::ProtectedReservationTip;
use crate::reservation::ReleaseDisposition;
use crate::reservation::ReservationLifecycleSnapshot;

const CONTRACT_NAME: &str = "cargo-berth-output";

const PYTHON_SHELL_VALIDATOR: &str = r#""""Generated by cargo-berth. Do not edit."""

from typing import TypeGuard


def _is_string_list(value: object) -> TypeGuard[list[str]]:
    return isinstance(value, list) and all(isinstance(item, str) for item in value)


def _is_rendered_output_block(value: object) -> bool:
    return (
        isinstance(value, dict)
        and isinstance(value.get("summary"), str)
        and isinstance(value.get("detail"), str)
    )


def _is_rendered_output_block_list(value: object) -> bool:
    return isinstance(value, list) and all(
        _is_rendered_output_block(item) for item in value
    )


def _valid_presentation(value: object) -> bool:
    if not isinstance(value, dict):
        return False
    kind = value.get("kind")
    if not isinstance(kind, str):
        return False
    if kind != "rendered_blocks":
        return True
    return _is_rendered_output_block_list(value.get("blocks"))


def valid_contract_envelope(envelope: object) -> bool:
    """Return whether decoded JSON provides the stable front-end shell."""
    return (
        isinstance(envelope, dict)
        and isinstance(envelope.get("verb"), str)
        and isinstance(envelope.get("status"), str)
        and isinstance(envelope.get("exit_code"), int)
        and not isinstance(envelope.get("exit_code"), bool)
        and isinstance(envelope.get("message"), str)
        and _is_string_list(envelope.get("reservations"))
        and _is_string_list(envelope.get("blocked_by"))
        and _valid_presentation(envelope.get("presentation"))
    )
"#;

const JQ_SHELL_VALIDATOR: &str = r#"# Generated by cargo-berth. Do not edit.
def cargo_berth_string_array:
  type == "array" and all(.[]; type == "string");

def cargo_berth_integer:
  type == "number" and floor == .;

def cargo_berth_valid_rendered_output_block:
  type == "object"
  and (.summary | type == "string")
  and (.detail | type == "string");

def cargo_berth_rendered_output_block_array:
  type == "array" and all(.[]; cargo_berth_valid_rendered_output_block);

def cargo_berth_valid_presentation:
  type == "object"
  and (.kind | type == "string")
  and (
    if .kind == "rendered_blocks"
    then (.blocks | cargo_berth_rendered_output_block_array)
    else true
    end
  );

def cargo_berth_valid_contract_envelope:
  type == "object"
  and (.verb | type == "string")
  and (.status | type == "string")
  and (.exit_code | cargo_berth_integer)
  and (.message | type == "string")
  and (.reservations | cargo_berth_string_array)
  and (.blocked_by | cargo_berth_string_array)
  and (.presentation | cargo_berth_valid_presentation);
"#;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
struct ConsumerArtifacts {
    envelope_validation_jq: String,
    status_payload_tables:  String,
}

#[derive(Debug, Deserialize)]
struct CheckedContract {
    consumer_artifacts: ConsumerArtifacts,
}

type GeneratedSchemas = BTreeMap<String, Value>;

#[derive(Clone, Copy)]
enum ClosedValueSelectorTransformStatus<'schema> {
    Complete,
    Failed(&'schema Value),
}

/// Regenerate the checked-in output contract entirely in memory.
fn generate_output_contract() -> Result<String, Error> {
    generate_output_contract_with_reservation_lifecycle::<ReservationLifecycleSnapshot>()
}

fn generate_output_contract_with_reservation_lifecycle<LifecycleSchema: JsonSchema>()
-> Result<String, Error> {
    let contract = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "contract": CONTRACT_NAME,
        "version": OUTPUT_CONTRACT_VERSION,
        "consumer_artifacts": render_consumer_artifacts(),
        "schemas": generated_schemas::<LifecycleSchema>()?,
    });
    let mut serialized = serde_json::to_string_pretty(&contract)?;
    serialized.push('\n');
    Ok(serialized)
}

/// Reproduce both consumer files from a serialized checked-in contract.
fn consumer_artifacts_from_contract(serialized_contract: &str) -> Result<(String, String), Error> {
    serde_json::from_str::<Value>(serialized_contract)?;
    let regenerated = render_consumer_artifacts();
    Ok((
        regenerated.status_payload_tables,
        regenerated.envelope_validation_jq,
    ))
}

/// Read the consumer bytes embedded for installation after reproducibility validation.
fn embedded_consumer_artifacts(serialized_contract: &str) -> Result<(String, String), Error> {
    let checked_contract = serde_json::from_str::<CheckedContract>(serialized_contract)?;
    Ok((
        checked_contract.consumer_artifacts.status_payload_tables,
        checked_contract.consumer_artifacts.envelope_validation_jq,
    ))
}

fn generated_schemas<LifecycleSchema: JsonSchema>() -> Result<GeneratedSchemas, Error> {
    let mut schemas = BTreeMap::new();
    schemas.insert(
        "canonical_worktree_root".to_owned(),
        schema_value::<CanonicalWorktreeRoot>()?,
    );
    schemas.insert(
        "coordination_identity_rejection".to_owned(),
        schema_value::<CoordinationIdentityRejection>()?,
    );
    schemas.insert(
        "identity_payload".to_owned(),
        schema_value::<IdentityPayload>()?,
    );
    schemas.insert(
        "integration_evidence_status".to_owned(),
        schema_value::<IntegrationEvidenceStatus>()?,
    );
    schemas.insert(
        "integration_payload".to_owned(),
        schema_value::<IntegrationPayload>()?,
    );
    schemas.insert(
        "integration_proof".to_owned(),
        schema_value::<IntegrationProof>()?,
    );
    schemas.insert(
        "lost_integration_evidence_alert".to_owned(),
        schema_value::<LostIntegrationEvidenceAlert>()?,
    );
    schemas.insert(
        "output_envelope".to_owned(),
        schema_value::<OutputEnvelope>()?,
    );
    schemas.insert(
        "output_facts".to_owned(),
        checked_schema_value(output::output_facts_schema())?,
    );
    schemas.insert(
        "protected_reservation_tip".to_owned(),
        schema_value::<ProtectedReservationTip>()?,
    );
    schemas.insert(
        "release_disposition".to_owned(),
        schema_value::<ReleaseDisposition>()?,
    );
    schemas.insert(
        "replay_failure".to_owned(),
        schema_value::<ReplayFailurePayload>()?,
    );
    schemas.insert(
        "reservation_lifecycle".to_owned(),
        schema_value::<LifecycleSchema>()?,
    );
    schemas.insert(
        "reservation_lifecycle_query".to_owned(),
        schema_value::<ReservationLifecycleQueryPayload>()?,
    );
    schemas.insert(
        "resolve_payload".to_owned(),
        schema_value::<ResolvePayload>()?,
    );
    Ok(schemas)
}

fn schema_value<SchemaType: JsonSchema>() -> Result<Value, Error> {
    checked_schema_value(schemars::schema_for!(SchemaType))
}

fn checked_schema_value(schema: Schema) -> Result<Value, Error> {
    let schema_value = serde_json::to_value(schema)?;
    assert_closed_value_selector_transforms_completed(&schema_value)?;
    Ok(schema_value)
}

fn assert_closed_value_selector_transforms_completed(schema: &Value) -> Result<(), Error> {
    match closed_value_selector_transform_status(schema) {
        ClosedValueSelectorTransformStatus::Complete => Ok(()),
        ClosedValueSelectorTransformStatus::Failed(failure) => {
            Err(<Error as serde::ser::Error>::custom(format!(
                "closed-value selector transform failed: {failure}"
            )))
        },
    }
}

fn closed_value_selector_transform_status(
    schema: &Value,
) -> ClosedValueSelectorTransformStatus<'_> {
    match schema {
        Value::Array(members) => nested_transform_status(members),
        Value::Object(members) => members
            .get(CLOSED_VALUE_SELECTOR_TRANSFORM_FAILURE_KEY)
            .map_or_else(
                || nested_transform_status(members.values()),
                ClosedValueSelectorTransformStatus::Failed,
            ),
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {
            ClosedValueSelectorTransformStatus::Complete
        },
    }
}

fn nested_transform_status<'schema>(
    members: impl IntoIterator<Item = &'schema Value>,
) -> ClosedValueSelectorTransformStatus<'schema> {
    members
        .into_iter()
        .find_map(
            |member| match closed_value_selector_transform_status(member) {
                ClosedValueSelectorTransformStatus::Complete => None,
                failed @ ClosedValueSelectorTransformStatus::Failed(_) => Some(failed),
            },
        )
        .unwrap_or(ClosedValueSelectorTransformStatus::Complete)
}

fn render_consumer_artifacts() -> ConsumerArtifacts {
    ConsumerArtifacts {
        envelope_validation_jq: JQ_SHELL_VALIDATOR.to_owned(),
        status_payload_tables:  PYTHON_SHELL_VALIDATOR.to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;

    use schemars::Schema;
    use serde_json::Value;
    use serde_json::json;

    use super::CONTRACT_NAME;
    use super::checked_schema_value;
    use super::consumer_artifacts_from_contract;
    use super::embedded_consumer_artifacts;
    use super::generate_output_contract;
    use crate::output::OUTPUT_CONTRACT_VERSION;
    use crate::output::closed_value_selects_object_shape;

    const CHECKED_CONTRACT: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/cargo-berth/generated/output-contract.json"
    );

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    #[test]
    fn generated_artifacts_are_reproducible_from_the_checked_in_contract() -> TestResult {
        let generated = generate_output_contract()?;
        if std::env::var_os("CARGO_BERTH_REGENERATE_OUTPUT_CONTRACT").is_some() {
            if let Some(parent) = Path::new(CHECKED_CONTRACT).parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(CHECKED_CONTRACT, &generated)?;
        }
        let checked = fs::read_to_string(CHECKED_CONTRACT)?;
        assert_eq!(generated, checked);

        let regenerated = consumer_artifacts_from_contract(&checked)?;
        let embedded = embedded_consumer_artifacts(&checked)?;
        assert_eq!(regenerated, embedded);
        Ok(())
    }

    #[test]
    fn generated_contract_contains_the_current_shell_and_phase_wires() -> TestResult {
        let generated = generate_output_contract()?;
        let contract: Value = serde_json::from_str(&generated)?;
        assert_eq!(contract["contract"], CONTRACT_NAME);
        assert_eq!(contract["version"], OUTPUT_CONTRACT_VERSION);

        assert!(generated.contains("output_contract_version"));
        assert!(generated.contains("presentation"));
        assert!(generated.contains("not_provided"));
        assert!(generated.contains("rendered_blocks"));
        assert!(generated.contains("ambiguous_active_run_reservations"));
        assert!(generated.contains("first_touch_reservation_selection"));
        Ok(())
    }

    #[test]
    fn selector_transform_failures_stop_output_contract_generation() -> TestResult {
        let malformed_schemas = [
            json!({
                "type": "object",
                "properties": {"kind": {"type": "string"}},
                "required": ["kind"],
            }),
            json!({
                "type": "object",
                "properties": {"kind": {"type": "string", "enum": []}},
                "required": ["kind"],
            }),
            json!({
                "type": "object",
                "properties": {"kind": {"type": "string", "enum": ["file", "file"]}},
                "required": ["kind"],
            }),
            json!({
                "type": "string",
                "properties": {"kind": {"type": "string", "enum": ["file", "tree"]}},
                "required": ["kind"],
            }),
            json!({
                "type": "object",
                "properties": {"kind": {"type": "string", "enum": ["file", "tree"]}},
            }),
        ];

        for schema_value in malformed_schemas {
            let mut schema = Schema::try_from(schema_value)?;
            closed_value_selects_object_shape(&mut schema);
            assert!(checked_schema_value(schema).is_err());
        }
        Ok(())
    }
}
